# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simpsons < Formula
  desc "TUI analytics dashboard for Claude Code sessions"
  homepage "https://github.com/rudrakshsisodia/simpsons"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrakshsisodia/simpsons/releases/download/v0.1.6/simpsons_0.1.6_darwin_amd64.tar.gz"
      sha256 "7af84a82922efba8c002d69d818d328967444dc07b455da92287925d5b591aba"

      define_method(:install) do
        bin.install "simpsons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrakshsisodia/simpsons/releases/download/v0.1.6/simpsons_0.1.6_darwin_arm64.tar.gz"
      sha256 "fde28b0c499790fb3d5170ffe3e00321c6f9c4a76f77b0bddde2f8cb10be2fe2"

      define_method(:install) do
        bin.install "simpsons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrakshsisodia/simpsons/releases/download/v0.1.6/simpsons_0.1.6_linux_amd64.tar.gz"
      sha256 "bdb402f6bc3b93eb34cad2299fe73a446d138edf44ad3178584a18ddfe9b9cff"
      define_method(:install) do
        bin.install "simpsons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrakshsisodia/simpsons/releases/download/v0.1.6/simpsons_0.1.6_linux_arm64.tar.gz"
      sha256 "db2ce5fce74cb6457558b9d69adf7f1dfd1571fd7237108530e501478a42d978"
      define_method(:install) do
        bin.install "simpsons"
      end
    end
  end
end
